// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
// find the sum of the even-valued terms.

generateFibNumber = function(array,limit,evenFibNumbers) {
	var newFibNum = array[array.length -1] + array[array.length -2];

	if (newFibNum < limit) {
		array.push(newFibNum);

		if (!(newFibNum%2)) evenFibNumbers.push(newFibNum);
		generateFibNumber(array,limit,evenFibNumbers);
	} 

	return evenFibNumbers;
};

var fibonacci = function(limit) {
	var evenFibNumbers = [2];
	var fibNumbers = generateFibNumber([1,2],limit,evenFibNumbers);

	var sum = fibNumbers.reduce(function(prev,curr) {
		return prev+curr;
	});

	console.log("The sum is: ",sum);
};